function test() 
    String firstPart, stmt
    string which = $WhichDB

    switch( which ) 
        case "HANA", "Oracle"
           firstPart = "select name, dataid from dtree where exists "
        end
        case "MSSQL"
            firstPart = "select NAME, DATAID from dtree where exists "
        end
        case "SQLite"
            firstpart = "select NAME, DATAID, parentid from dtreecore where exists "
        end
    end

    Integer i
    for i = 1 to 100
        firstpart += " " 
    end

    if( $SyntergyCore.SQLUtils.IsOracle() ) 
        stmt += "select dataid, Ownerid From " + $DT_TABLE + " where Dataid = :A1" 
    else
        stmt += "select DaTaId, ownerid, " + \
            "userid, name From " + \
                $DT_TABLE + " where " + \
                "dataID = :A1 order by parentiD desc" 
    end

    String realStmt = firstPart + "(" + stmt + ") order by extendeddata"

    .ExecSQL( prgCtx, realStmt, {} )
end